// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv9z0srB5Ew-hn_IfHcgN-Jedyhx9UhvI',
    appId: '1:126797725134:android:266f4ce6562d47e2c9bf9f',
    messagingSenderId: '126797725134',
    projectId: 'cash-wise-tamiresbassi-2025',
    storageBucket: 'cash-wise-tamiresbassi-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjMFE0Js4x-hxEma5rBoSWuo_ETxLR84Q',
    appId: '1:126797725134:ios:ab20f6a641eab773c9bf9f',
    messagingSenderId: '126797725134',
    projectId: 'cash-wise-tamiresbassi-2025',
    storageBucket: 'cash-wise-tamiresbassi-2025.firebasestorage.app',
    iosBundleId: 'com.example.cashWise',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBh47GuoGIcTp5JowjN0H4gE8EqGxbOXI',
    appId: '1:126797725134:web:6b9fd447a346fd20c9bf9f',
    messagingSenderId: '126797725134',
    projectId: 'cash-wise-tamiresbassi-2025',
    authDomain: 'cash-wise-tamiresbassi-2025.firebaseapp.com',
    storageBucket: 'cash-wise-tamiresbassi-2025.firebasestorage.app',
    measurementId: 'G-PWXQSJBCDC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjMFE0Js4x-hxEma5rBoSWuo_ETxLR84Q',
    appId: '1:126797725134:ios:ab20f6a641eab773c9bf9f',
    messagingSenderId: '126797725134',
    projectId: 'cash-wise-tamiresbassi-2025',
    storageBucket: 'cash-wise-tamiresbassi-2025.firebasestorage.app',
    iosBundleId: 'com.example.cashWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBh47GuoGIcTp5JowjN0H4gE8EqGxbOXI',
    appId: '1:126797725134:web:5412d7e6b6797b28c9bf9f',
    messagingSenderId: '126797725134',
    projectId: 'cash-wise-tamiresbassi-2025',
    authDomain: 'cash-wise-tamiresbassi-2025.firebaseapp.com',
    storageBucket: 'cash-wise-tamiresbassi-2025.firebasestorage.app',
    measurementId: 'G-8D308ZJ7CP',
  );

}